### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by zidad** [PaulTrampert/dotnet-version#1]
in your docs: "Tool to update the version of a project.json"

What's the recommended approach on how to do this?

Thanks!

**Comment by PaulTrampert** [comment]
Ah sorry for the confusion. I'll need to update the README, but the short version is this:

Include this in the tools section of your project.json. It's available via nuget.

```
{
  "tools": {
    "dotnet-version": "1.1.0"
  }
}
```

Then from the command prompt, change your working directory to the root of your project. For example if your project.json is in C:\Users\Paul\Project, you would cd to C:\Users\Paul\Project. You can then change the version string in the project.json with `dotnet version <yourversionnumber>`.

The primary purpose of this is build servers. Most projects that I've worked on don't know the actual release version until it's time to release, so I needed a way to be able to specify the version number at build time. So the build script might do something like this:

```
dotnet version 1.3.0
dotnet pack -c Release
git commit -a -m "Release 1.3.0"
git tag 1.3.0
dotnet version 1.3.1-*
git commit -a -m "Next working version"
```

This would set the version to 1.3.0, then build and pack the project.

**Comment by zidad** [comment]
Thanks a lot!
