### ISSUE TITLE
support to csproj

### ISSUE THREAD

**Issue by biasmey** [PaulTrampert/dotnet-version#9]
Hello ,
Are you will be planning add support to csproj projects ?

**Comment by PaulTrampert** [comment]
Hi biasmey,

The csproj based tooling actually supports directly setting the version prefix by passing the msbuild property `/p:VersionPrefix=1.2.3` to any relevant `dotnet` commands (namely `pack`, `publish`, and `build`). Therefore, this tool is no longer needed once you migrate to csproj tooling, and I will not be continuing development.

Paul

**Comment by biasmey** [comment]
Thank you so much
